GET http://localhost:4000/mahasiswa

###
GET http://localhost:4000/mahasiswa/1

###
POST http://localhost:4000/mahasiswa
Content-Type: application/json

{
    "name":"Ahmad Muzaki SA", 
    "address": "Karangcengek"
}

###
PATCH http://localhost:4000/mahasiswa/1
Content-Type: application/json

{
    "name":"Ahmad Muzaki Salman Alfaris", 
    "address": "Karangcengek"
}