GET http://localhost:3000/mahasiswa

###
GET http://localhost:3000/mahasiswa/2

###
POST http://localhost:3000/mahasiswa
Content-Type: application/json

{
    "name":"Ahmad Muzaki SA", 
    "address": "Karangcengek"
}